#!/usr/bin/env bash
set -euo pipefail

build_dir="${BUILD_DIR:-build}"
yosys="${YOSYS:-yosys}"
rtl_flist="${RTL_FLIST:-filelists/rtl.f}"
top="axis_pkt_router"
summary="docs/synthesis-summary.md"
log="$build_dir/synth-report.log"
ys="$build_dir/synth-report.ys"

mkdir -p "$build_dir"

rtl_srcs="$(tr '\n' ' ' < "$rtl_flist")"
yosys_version="$("$yosys" -V)"

cat > "$ys" <<EOF_YS
read_verilog -sv -DSYNTHESIS $rtl_srcs
hierarchy -top $top
proc
memory -nomap
opt
check
stat
tee -o $build_dir/synth-hierarchy.txt hierarchy
tee -o $build_dir/synth-stat.txt stat
tee -o $build_dir/synth-check.txt check
EOF_YS

"$yosys" -s "$ys" > "$log" 2>&1

cell_count="$(awk '/^[[:space:]]*[0-9]+ cells$/ {value=$1} END {if (value == "") print "unknown"; else print value}' "$build_dir/synth-stat.txt")"
memory_count="$(awk '/^[[:space:]]*[0-9]+[[:space:]]+[$]mem/ {value=$1} END {print value + 0}' "$build_dir/synth-stat.txt")"

{
  echo "# Synthesis Summary"
  echo
  echo "Generated by \`make synth-report\`."
  echo
  echo "- Tool: \`${yosys_version}\`"
  echo "- Top module: \`${top}\`"
  echo "- RTL filelist: \`${rtl_flist}\`"
  echo "- Parameter configuration: default 2 ingress, 4 egress, \`DATA_W=32\`, \`DEST_W=2\`, \`INGRESS_MAX_PKT_BEATS=64\`, \`COUNTER_W=32\`"
  echo "- Flow: generic technology-independent Yosys parse, hierarchy, process lowering, memory preservation, optimization, check, and statistics"
  echo "- Total generic cell count: \`${cell_count}\`"
  echo "- Inferred memory cells reported by generic stat: \`${memory_count}\`"
  echo "- Detailed generated log: \`${log}\`"
  echo "- Detailed generated statistics: \`$build_dir/synth-stat.txt\`"
  echo
  echo "This is a generic synthesis/elaboration result, not an ASIC area, FPGA timing, or implementation-quality claim."
} > "$summary"

echo "Wrote $summary"
echo "Wrote $log"
